### ISSUE TITLE
Hacer responsive a la página

### ISSUE THREAD

**Issue by rferromoreno** [unsiaw/proyecto1#2]
Hacer que funcione en celulares/tables/pcs.

Hay que revisar el tema de las tablas en CSS en Bootstrap y además vamos a tener que fijar un width según el container del canvas.

**Comment by matiaschap** [comment]
estuve mirando esto, que hace responsive n canvas 
https://devcode.la/tutoriales/elemento-canvas-responsive/
https://jsfiddle.net/lannymcnie/4yy08pax/
